channels:
  - conda-forge
dependencies:
  - python =3.11
  - jupyterlab
  - jupyter-book
  - ipykernel
  - ipympl
  - ipywidgets
  - pyiron
  - pyiron_base
  - pyiron_atomistics
  - pyiron_contrib
  - pyiron_potentialfit
  - pyiron_gpl
  - pyiron-data
  - pyiron_workflow =0.4.1
  - nbgitpuller =1.2.0
  - python-ace =0.2.8
  - calphy =1.3.1
  - iprpy-data
  - sphinxdft >=2.7.0
  - sphinxdft-data
  - nglview
  - numpy >=1.26.0
  - pyscal3
  - sqsgenerator
  - pymatgen
  - pydantic >=2.3.0
  - randspg
  - mp-api =0.37.5
  - typing-extensions =4.8.0
  - mpi4py
  - pylammpsmpi =0.2.13


